### ISSUE TITLE
Nessesário configurações de criador

### ISSUE THREAD

**Issue by AelMartins** [Leonardo-henriqu2/PI---5-v2#1]
Para criar um template para que as pessoas possam relatar de modo privado uma vulnerabilidade de segurança, a opção **Private vulnerability reporting** precisa estar ativada.

Por favor, acesse as configurações do repositório e selecione a opção "código de segurança" na sessão Segurança. Em seguida ative a opção relato "privado de vulnerabilidade".

Você pode seguir as orientações desta documentação: [Como configurar relatórios privados de vulnerabilidades em um repositório](https://docs.github.com/pt/code-security/security-advisories/working-with-repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository)

**Comment by Leonardo-henriqu2** [comment]
Feito meu rei!
